### ISSUE TITLE
Multiple Universes

### ISSUE THREAD

**Issue by Olivierdemoustier** [tigoe/sACNSource#3]
Would like to see a way to send more than 1 universe. Tried using more than 1 instance of sacnsource. But seconde universe would not do anything usefull.
Sorry, multiple instances does work..... I had problem with the receivers....
Tip: set ip in secrets to 2.255.255.255  for multicast

**Comment by tigoe** [comment]
Sorry, I haven't looked at this repo in a while. You should be able to do multiple universes by calling `setUniverse()` before you start each packet.  Something like this (warning: untested, as I don't have the equipment at home to test multiple universes): 

````
// for universes 1-3:
for (int universe = 1; universe < 4; universe++) {
  myController.setUniverse(universe);
  // set DMX channel values to 0:
    for (int dmxChannel = 0; dmxChannel < 513; dmxChannel++) {
      myController.setChannel(dmxChannel, 0);
    }
   // send data frame for this universe:
    myController.sendPacket(SECRET_SACN_RECV);
} // iterate to the next universe
````

You can do the same with sourceName and UUID using `setSourceName()` and `setUuid()`. None of these three commands require a new initializer to change the property.

**Comment by tigoe** [comment]
By the way, on multicast, the sACN standard formula is  239.255.universeHighByte.universeLowByte. ETC has a [calculator for this](https://support.etcconnect.com/ETC/Networking/General/sACN_Multicast_Calculator)

**Comment by tigoe** [comment]
Hope that helps.
